version: "3.5"


services:    
    database:
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRE_PASSWORD=ignite
            - POSTGRE_DB=rentx
        volumes: 
            - pgdata:/data/postgres

    app:
        build: .
        container_name: rentx
        restart: always
        ports:
           - 3333:3333
        volumes:
            - .:/usr/app 
        links: 
            - database
        depends_on: 
            - database

volumes: 
    pgdata:
        driver: local
