version: "3.5"


services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
            - '5432:5432'
        environment: 
            - POSTGRES_USER=docker
            - POSTGRE_PASSWORD=database_ignite
            - POSTGRE_DB=rentx
        volumes: 
            - pgdata:/data/postgres
        network_mode: host
    app:
        build: .
        container_name: rentx
        ports:
           - '3333:3333'
        volumes:
            - .:/usr/app 
        network_mode: host

volumes: 
    pgdata:
        driver: local
